version: "3.8"
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: f1db
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: on-failure        
