version: "3.8"
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: f1db
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always

